apiVersion: v1
kind: Service
metadata:
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "k8s-instance.fullname" . }}
  labels:
    {{- include "k8s-instance.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "k8s-instance.selectorLabels" . | nindent 4 }}
  metadata:
    {{- with .Values.serviceAnnotations }}
    annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    labels:
    {{- include "k8s-instance.labels" . | nindent 4 }}